<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf8" />
  <meta name="viewport" content="width=device-width,height=device-height">
  {{ assets.outputCss('cssHeader') }}
</head>
<body>
	<div class="c-wrapper">
    <div class="contain">

			<?php $this->partial("blocks/templates") ?>
      <div class="text-center row ">
        <div class="col-xs-3 text-left" style="padding-left:6px;">
          <ul class="no-bullet">
            <li>{{ link_to('index/login', '<span class="glyphicon glyphicon-signal"></span> Статистика', 
              'class': 'btn btn-sm btn-link border-radius-0 no-decoration', 
              'title': 'Статистика',
              'disabled': 'true') }}
            </li>
          {% if aclAdapter.check(userAdapter, 'log', 'index') %}
            <li>{{ link_to('log/index', '<span class="glyphicon glyphicon-envelope"></span> Уведомления', 
              'class': 'btn btn-sm btn-link border-radius-0 no-decoration', 
              'title': 'Уведомления') }}
            </li>
          {% endif %}
          {% if aclAdapter.check(userAdapter, 'work', 'index') %}
            <li>{{ link_to('work/index', '<span class="glyphicon glyphicon-list"></span> Дела', 
              'class': 'btn btn-sm btn-link border-radius-0 no-decoration', 
              'title': 'Дела') }}
            </li>
          {% endif %}
          </ul>
          
        </div>
        <div class="col-xs-6">
          {{ link_to('', '<img src="/img/Hogwarts_Logo.png" class="logo center">') }}
        </div>
        <div class="col-xs-3 text-right">
          {% if userAdapter.loggedIn() === false %}
            <script src="//ulogin.ru/js/ulogin.js"></script>
            <div id="uLogin" data-ulogin="display=buttons;fields=first_name,last_name,photo;redirect_uri={{ url('index/oauth')|url_encode }};receiver={{ url('')~'xd_custom.html'|url_encode }}">
              <button type="button" class="btn btn-default border-radius-0" title="вход" data-uloginbutton = "vkontakte"><span class="glyphicon glyphicon-log-in"></span></button>
            </div>
          {% else %}
            {{ link_to('index/logout', '<button type="button" class="btn btn-default border-radius-0" title="выход"><span class="glyphicon glyphicon-log-out"></span></button>') }}
          {% endif %}
        </div>
      </div>
    
      {{ content() }}
    </div>
  </div>
	
  
  {{ assets.outputJs('jsHeader') }}
  <script>
		$(function(){
			App.init();	
		})
	</script>
</body>
</html>