
<div class="row">
	{% set class = ['1':'success', '-1':'warning'] %}
	{% for type, works  in filteredWorks %}
    <div class="col-xs-6">
      <table class="table works">
        {% for work in works %}
        	<tr class="{{ class[type] }} row{{ work.id }}" data-id="{{ work.id }}">
          	<td class="word-wrap-50" data-field="name" contenteditable="true">{{ work.name }}</td>
          	<td data-field="cost" contenteditable="true">{{ work.cost }}</td>
          	<td>
              <button class="btn btn-default btn-xs btn-danger" onClick="App.data.removeWork({{ work.id }});"><span class="glyphicon glyphicon-remove"></span></button>
              <i class="glyphicon glyphicon-move icon-move dragging pull-right"></i>
            </td>
       		</tr>
        {% endfor %}
      </table>
    </div>
  {% endfor %}
</div>
<script>
	window.onload = function(){
		App.page.workEditingSubscribe();	
		App.page.tableSortable();
	}
</script>

<h3>Добавить дело</h3>
{% if errors %}
<div class="alert alert alert-danger">
	<ul>
	{% for error in errors %}
  	<li>{{ error }}</li>
  {% endfor %}
  </ul>
</div>
{% endif %}
{{ form('work/index', 'method': 'post', 'class': 'margin-top-10') }}
  <div class="row">
    <div class="col-xs-4"><label class="label-df">Название</label></div>
    <div class="col-xs-8">
      <input type="text" name="data[name]" class="form-control" value="{{ data['name'] }}">
    </div>
  </div>
  <div class="row margin-top-10">
    <div class="col-xs-4"><label class="label-df">Оценка</label></div>
    <div class="col-xs-8">
      <label><input type="radio" name="data[type]" value="1" {% if data['type'] == 1 %} checked {% endif %}> Положительная</label>
      <label><input type="radio" name="data[type]" value="-1" {% if data['type'] == -1 %} checked {% endif %}> Отрицательная</label>
    </div>
  </div>
  <div class="row margin-top-10">
    <div class="col-xs-4"><label class="label-df">Стоимость</label></div>
    <div class="col-xs-8">
      <input type="number" min="1" max="10" name="data[cost]" class="form-control" value="{{ data['cost']|default }}">
    </div>
  </div>
  <input type="submit" class="btn btn-default border-radius-0 margin-top-10" value="Добавить">
</form>